markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

defaults:
  - scope:
      path: ""
    values:
      layout: default

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: false
